language: node_js
node_js:
  - '0.12'
after_success:
  - npm run report-coverage
  - '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && [ "x$TRAVIS_TAG" != "x" ] && npm
    run publish:cdn'
deploy:
  provider: script
  script: echo "npm credentials were revoked on 2018-07-12. We regenerated many
    credentials, but this repository had no changes in at least 18 months and
    was skipped. Reconfigure npm deployments. -omsmith"; exit 1
  on:
    tags: true
    repo: Brightspace/superagent-d2l-cors-proxy
env:
  global:
    - secure: m3QDtbYZGiMrWRtPUTwaEox2aDEXV83XFxDO9s+0aMiGUuNKru5Xs12Gi7mQ9AXeJHkHdmZFJonjuk1/TyYTJneq+fupvrSO0ZrXvoT4lJN4dH99FRKR2OtovtBZnfzlQ1BRlg639yoaqIOKTKjccRu8r0lf+NbG1r8Ls6ngVfZkrz2R5H1yDFKP359ynUxMALcMgRl3naseb2Z/9nXpUs0Z3E4wDhXt3W8ixMnOiF8ONMNOC+82roWrzWMI6GVyKHTv661jzogERcC82TMg4XBA7ubEfa4pqtxHEbUrmc8CP9UNEdJ0VNYtPB0uWEounpYCkRJ0eUWAf1zTK+/CfiOqKITTnJ0zF0ryDzu0LNPCykrSmqRH8f4oVp+sPgbivWGSeZsh2crPe7CjjtDT0/vXWX3bkQ0OCikPlz+SUTUZIlasBU2//tGPxS3JkiNEkpN4JcZpG3tGHJSP2paN0bVv9tSVaFDSbQB36OW2lbZb3ho6cWuyhsYZ5bm3s5eABII11F87r6q8m19OqSRRsGvVn9asTPdODtD8zA52RO0u5cTebyCQSu9MGevBTFK0MIqlMwEY7Vd8xD2UVwxs/coKQPcatXPTe3l6CFStFMbiHkC4mcaiJiSNAP/73Fu7CjpZoZ1x1N6RErydB/yNliYIhfMt+8pZJ3p6XvRdgGE=
    - secure: oysHeO7fVZ4yqYTbKPo2GYkU9KMIxXpVlHGFPCb9+Ze98facqwpPSGru/nixF6Bf+yjXB8QwDeb3pGY8OxPRyFKapBBRwnwY3+18MVNYADeNq0/x+ywPu9iX2tt+NfRhqj+RN4x0k4erN+UUjRC/Rp1w9LpBZnb+r1SAEQqT78yQ5zOQycAbszF5UNWcv+3kjGUFoWKQfmJHNC2gcGPOA8aPWIlPGKQrtB+P8OBBR4WH5j4VehrqE6mrzFrkisfRDtMd8/zQ7jNuofNuSZHfMyk2tV9LACvRD/9J2h3QpGQzFfRnhk4wyvhrf/M8fKd74ha1ic+/407C8C2w1m39J9PKfyIlSlmCthhmeimc0xHNnEDVPwrz6S+XQ03fDCi7mNMTuyxjuQR0Lfj9KVaZSCYuDO9cf2Irb6GgzUZ6ZJ9vSMtM1e2lnUAFbAYXDVPxUXuBBOoSC0NMNOpKEqxbpRFVFpeRAIpVQa2eUl6HN6veBKP1cuErT78uX2qMYwvHfN1E+svSu2JEWOkUESpa31bRlx5mz3eGAUDYAbjc0i/zK+g5M46bi4sxDLUb93erPKXAI8mhE4c4DqBqbeJCVW9yJFJypk3bEiDrNFOJDfvqbg7U76CCVpNtny6Rp/gW7bavQZBSrZOgt+IRy1RPw7As9+CLbrhdsCMcLWxxnHE=
